In [ ]:
s = 0
n = 10
for i in range(n):
    s += i + 1

s

In [ ]:
s_1 = 0.0
n = 10
for i in range(n):
    s_1 += 1.0 / (i + 1) ** 2

s_1

In [ ]:
import numpy as np

In [ ]:
np.pi

In [ ]:
e_n = np.abs(s_1 - (np.pi**2) / 6)
e_n

In [ ]:
def calc_partial_sum(n):
    s = 0
    for i in range(n):
        s += 1 / (i + 1) ** 2
    return s


def err(n):
    e_n = np.abs(calc_partial_sum(n) - (np.pi**2) / 6)
    return e_n

In [ ]:
err(100)

In [ ]:
err(1000)

In [ ]:
err(10000000)

In [ ]:
s = range(5)
print(range(5))

In [ ]:
import numpy as np

s: float128 = 50
print(s)

In [1]:
import numpy as np

In [9]:
A = np.array([[2, -4, 4], [1, -2, 3], [3, 2, -4]], dtype=float)
b = np.array([-10, -6, 11], dtype=float)


print(A)
print(A[0])
print(b)
print(b[1])

[[ 2. -4.  4.]
 [ 1. -2.  3.]
 [ 3.  2. -4.]]
[ 2. -4.  4.]
[-10.  -6.  11.]
-6.0


In [21]:
import numpy as np

a= np.array([[2, -4, 4], [1, -2, 3], [3, 2, -4]], dtype=float)
b = np.array([-10, -6, 11], dtype=float)

for k in range(3):


    a_max = np.abs(a[k, k])
    i_max = k


    for i in range(k, 3):


        if np.abs(a[i, k]) > a_max:


            a_max = np.abs(a[i, k])
            i_max = i


    if a_max < 1e-10:


        print("A is singular")


    if i_max != k:


        for j in range(3):


            a[k, j], a[i_max, j] = a[i_max, j],a[k, j]
        b[k], b[i_max] = b[i_max], b[k]


    for l in range(k + 1, 3):

        lk=-a[l,k]
        kk=a[k,k]
        #a[l] +=a[k] * (-a[l, k] / a[k, k])
        a[l] +=a[k]*(lk/kk)

        #b[l] += b[k] * (-a[l, k] / a[k, k])
        b[l] += b[k]*(lk/kk)


x = [0, 0, 0]


for m in reversed(range(3)):


    x[m] = b[m] / a[m, m]


    for n in range(m):


        b[n] -= a[n, m] * x[m]

x

[1.0, 2.0, -1.0]

In [ ]:
import numpy as np

def solve_lse(a,b):
    size=a.shape[0]
